"""refactor interview_reports table schema

Revision ID: 431ec86330e7
Revises: d0379f9fcd79
Create Date: 2025-09-05 22:48:16.489921

"""
from typing import Sequence, Union

from alembic import op
from app.core.config import settings
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '431ec86330e7'
down_revision: Union[str, Sequence[str], None] = 'd0379f9fcd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_tags_id'), table_name='vacancy_tags')
    op.drop_table('vacancy_tags')
    op.add_column('interview_reports', sa.Column('analysis_result', sa.JSON(), nullable=False))
    op.drop_column('interview_reports', 'final_summary_result')
    op.drop_column('interview_reports', 'speech_sense_result')
    op.drop_column('vacancies', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('status', sa.VARCHAR(length=14), server_default=sa.text("'DRAFT'"), nullable=False))
    op.add_column('vacancies', sa.Column('complexity', sa.String(length=50), nullable=True))
    op.add_column('interview_reports', sa.Column('speech_sense_result', sqlite.JSON(), nullable=True))
    op.add_column('interview_reports', sa.Column('final_summary_result', sqlite.JSON(), nullable=False))
    op.drop_column('interview_reports', 'analysis_result')
    op.create_table('vacancy_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=22), nullable=False),
    sa.Column('is_custom', sa.BOOLEAN(), nullable=True),
    sa.Column('speech_sense_dict_id', sa.VARCHAR(), nullable=True),
    sa.Column('vacancy_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('speech_sense_dict_id')
    )
    op.create_index(op.f('ix_vacancy_tags_id'), 'vacancy_tags', ['id'], unique=False)
    # ### end Alembic commands ###
