"""add is_viewed_by_hr to interview_report

Revision ID: b6c9cc01b537
Revises: b105ace4e225
Create Date: 2025-09-09 20:45:54.633114

"""
from typing import Sequence, Union

from alembic import op
from app.core.config import settings
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c9cc01b537'
down_revision: Union[str, Sequence[str], None] = 'b105ace4e225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_reports', sa.Column('is_viewed_by_hr', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_reports', 'is_viewed_by_hr')
    # ### end Alembic commands ###
