"""add vacancy status and tags model

Revision ID: d0379f9fcd79
Revises: 0b022bc7a944
Create Date: 2025-09-03 15:35:46.485558

"""
from typing import Sequence, Union

from alembic import op
from app.core.config import settings
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd0379f9fcd79'
down_revision: Union[str, Sequence[str], None] = '0b022bc7a944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('type', sa.Enum('HARD_SKILL', 'SOFT_SKILL', 'TOOL', 'UNIVERSAL_INCONFIDENCE',
                                              'UNIVERSAL_NEGATIVITY', 'UNIVERSAL_ACHIEVEMENT', name='vacancytagtype'),
                              nullable=False),
                    sa.Column('is_custom', sa.Boolean(), nullable=True),
                    sa.Column('speech_sense_dict_id', sa.String(), nullable=True),
                    sa.Column('vacancy_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('speech_sense_dict_id')
                    )
    op.create_index(op.f('ix_vacancy_tags_id'), 'vacancy_tags', ['id'], unique=False)
    op.create_table('interview_reports',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('speech_sense_result', sa.JSON(), nullable=True),
                    sa.Column('final_summary_result', sa.JSON(), nullable=False),
                    sa.Column('session_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('session_id')
                    )
    op.create_index(op.f('ix_interview_reports_id'), 'interview_reports', ['id'], unique=False)
    op.add_column('interview_sessions', sa.Column('is_completed_correctly', sa.Boolean(), nullable=False))
    op.add_column('interview_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('vacancies', sa.Column('status',
                                         sa.Enum('DRAFT', 'PARSING', 'PREPARING_TAGS', 'PENDING_REVIEW', 'PUBLISHED',
                                                 'ARCHIVED', name='vacancystatus'), nullable=False,
                                         server_default='DRAFT'))
    op.add_column('vacancies', sa.Column('complexity', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'status')
    op.drop_column('interview_sessions', 'is_completed_correctly')
    op.drop_index(op.f('ix_interview_reports_id'), table_name='interview_reports')
    op.drop_table('interview_reports')
    op.drop_index(op.f('ix_vacancy_tags_id'), table_name='vacancy_tags')
    op.drop_table('vacancy_tags')
    # ### end Alembic commands ###
